# Experiment - 5 Text-PreProcessing

Importing Libraries

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

tfidfVectorizer = TfidfVectorizer()
countVectorizer = CountVectorizer()

Importing Data

In [3]:
data = pd.read_csv('elon_musk_tweets.csv')
data

,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet
0,1544379368478212100,Elon Musk,NaN,"Mars & Cars, Chips & Dips",2009-06-02 20:12:29+00:00,101240855,115,13503,True,2022-07-05 17:55:09+00:00,@BillyM2k I find the gold toe sock ‚Äì inevitabl...,NaN,Twitter for iPhone,335,6542,False
1,1544377493263720450,Elon Musk,NaN,"Mars & Cars, Chips & Dips",2009-06-02 20:12:29+00:00,101240806,115,13503,True,2022-07-05 17:47:42+00:00,"Sock Con, the conference for socks",NaN,Twitter for iPhone,1451,30753,False
2,1544377130590552064,Elon Musk,NaN,"Mars & Cars, Chips & Dips",2009-06-02 20:12:29+00:00,101240806,115,13503,True,2022-07-05 17:46:15+00:00,Always something new for the magazine cover an...,NaN,Twitter for iPhone,1284,28610,False
3,1544375575724400645,Elon Musk,NaN,"Mars & Cars, Chips & Dips",2009-06-02 20:12:29+00:00,101240806,115,13503,True,2022-07-05 17:40:05+00:00,@ExplainThisBob This guy gets it,NaN,Twitter for iPhone,131,3640,False
4,1544375148605853699,Elon Musk,NaN,"Mars & Cars, Chips & Dips",2009-06-02 20:12:29+00:00,101240806,115,13503,True,2022-07-05 17:38:23+00:00,Sock tech is so advanced that you can get pret...,NaN,Twitter for iPhone,1191,23790,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3536,1628998457645047808,Elon Musk,NaN,NaN,2009-06-02 20:12:29+00:00,130663340,182,19120,True,2023-02-24 06:01:12+00:00,Check out my spicy üå∂Ô∏è üî• OnlyGANs!! https://t.c...,NaN,Twitter for iPhone,19900,243266,False
3537,1628964700997267457,Elon Musk,NaN,NaN,2009-06-02 20:12:29+00:00,130663340,182,19120,True,2023-02-24 03:47:04+00:00,@derek_j_morris @pmarca Major problem,NaN,Twitter for iPhone,82,1219,False
3538,1628961847364681731,Elon Musk,NaN,NaN,2009-06-02 20:12:29+00:00,130663340,182,19120,True,2023-02-24 03:35:43+00:00,@EvaFoxU Nice,NaN,Twitter for iPhone,396,15353,False
3539,1628955011416743936,Elon Musk,NaN,NaN,2009-06-02 20:12:29+00:00,130663340,182,19120,True,2023-02-24 03:08:33+00:00,@DavidSacks A Russia-China alliance is inevita...,NaN,Twitter for iPhone,4472,41972,False
3540,1628878790616305664,Elon Musk,NaN,NaN,2009-06-02 20:12:29+00:00,130663340,182,19120,True,2023-02-23 22:05:41+00:00,@PeterDiamandis Yeah,NaN,Twitter for iPhone,479,13339,False

Extracting Texts from tweets

In [4]:

tweets = data['text']

### Making Bag of Words Vectorizer

In [5]:

bagOfWordsMatrix = countVectorizer.fit_transform(tweets).toarray()

In [6]:
bagOfWordsDataFrame = pd.DataFrame(bagOfWordsMatrix, columns=countVectorizer.get_feature_names_out())
bagOfWordsDataFrame.head()

,000,008zpnmegm,01fmxyrrvr,02100_eth,04efhdxate,0ecpd30qas,0faazmezra,0gzbmf83tt,0is89mjlky,0j1lmreobs,...,zpxyv0ef5a,zqdl9xgrur,zqfyymk3lp,zqqnolhcdn,zssbecker,zswitten,zubymusic,zutcsd7fiz,zydrar6mxf,Áß¶ÂßãÁöá
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Making TF IDF Vectorizer

In [7]:
tfIdfMatrix = tfidfVectorizer.fit_transform(tweets).toarray()

In [8]:
tfIdfDataFrame = pd.DataFrame(tfIdfMatrix, columns=tfidfVectorizer.get_feature_names_out())
tfIdfDataFrame.head()

,000,008zpnmegm,01fmxyrrvr,02100_eth,04efhdxate,0ecpd30qas,0faazmezra,0gzbmf83tt,0is89mjlky,0j1lmreobs,...,zpxyv0ef5a,zqdl9xgrur,zqfyymk3lp,zqqnolhcdn,zssbecker,zswitten,zubymusic,zutcsd7fiz,zydrar6mxf,Áß¶ÂßãÁöá
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0