In [15]:
import nltk
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import re
import pandas as pd

In [16]:
# downloading punkt tokenizer
nltk.download('punkt')
# downloading lemmatizer wordnet
nltk.download('wordnet')
# downloading the corpus of stopwords
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sudha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\sudha\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sudha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [17]:
df = pd.read_csv("spam.csv",encoding = "ISO-8859-1")

In [18]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [19]:
tweets=df['v2']
tweets

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [20]:
type(tweets)

pandas.core.series.Series

In [21]:
tweets.str.split

In [22]:
tweets

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [23]:
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

processedTweets = []

stopWords = set(stopwords.words('english'))

for tweet in tweets:
    # Convert the tweet to lowercase using REGEX
    for f in re.findall("([A-Z]+)", tweet):
        tweet = tweet.replace(f, f.lower())

    # Removing special characters and replacing them with a space
    tweet = re.sub("[^A-Za-z0-9]", " ", tweet, 0, re.IGNORECASE)
    
    # From a single sentence, store all the words 
    wordsInTweet = nltk.word_tokenize(tweet)
    
    # Filter out all the stop words
    wordsInTweet = [word for word in wordsInTweet if word not in stopWords]
    
    # Stem each of the tweets
    wordsInTweet = [stemmer.stem(word) for word in wordsInTweet if word not in stopWords]
    
    # Lemmatize each of the tweets
    wordsInTweet = [lemmatizer.lemmatize(word) for word in wordsInTweet]
    
    # Append them to a list
    processedTweets.append(wordsInTweet)
    
# print(processedTweets)

In [24]:
processedTweetsDataFrame = pd.DataFrame(data=processedTweets)
processedTweetsDataFrame.to_csv('processed-tweets.csv')

processedTweetsDataFrame

,0,1,2,3,4,5,6,7,8,9,...,68,69,70,71,72,73,74,75,76,77
0,go,jurong,point,crazi,avail,bugi,n,great,world,la,...,None,None,None,None,None,None,None,None,None,None
1,ok,lar,joke,wif,u,oni,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,free,entri,2,wkli,comp,win,fa,cup,final,tkt,...,None,None,None,None,None,None,None,None,None,None
3,u,dun,say,earli,hor,u,c,alreadi,say,None,...,None,None,None,None,None,None,None,None,None,None
4,nah,think,goe,usf,live,around,though,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,2nd,time,tri,2,contact,u,u,750,pound,prize,...,None,None,None,None,None,None,None,None,None,None
5568,b,go,esplanad,fr,home,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5569,piti,mood,suggest,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5570,guy,bitch,act,like,interest,buy,someth,el,next,week,...,None,None,None,None,None,None,None,None,None,None
5571,rofl,true,name,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [29]:
processedTweetsDataFrame.head()

,0,1,2,3,4,5,6,7,8,9,...,68,69,70,71,72,73,74,75,76,77
0,go,jurong,point,crazi,avail,bugi,n,great,world,la,...,None,None,None,None,None,None,None,None,None,None
1,ok,lar,joke,wif,u,oni,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,free,entri,2,wkli,comp,win,fa,cup,final,tkt,...,None,None,None,None,None,None,None,None,None,None
3,u,dun,say,earli,hor,u,c,alreadi,say,None,...,None,None,None,None,None,None,None,None,None,None
4,nah,think,goe,usf,live,around,though,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [43]:
' '.join(str(x) for x in processedTweetsDataFrame.iloc[1,0:10])

'ok lar joke wif u oni None None None None'